image: yschroeder/docker-texlive-tubslatex

build:
  tags:
    - tubslatex
  stage: build
  script:
    - make default
  artifacts:
    paths:
      - "*.pdf"
      - "*.png"

release:
  tags:
    - tubslatex
  stage: deploy
  only:
    - tags
  except:
    - branches
  script:
    - make release
  artifacts:
    paths:
      - "*.pdf"
      - "*.png"
