image: blang/latex

build:
  stage: build
  script:
    - make default
  artifacts:
    paths:
      - "*.pdf"
      - "*.png"

release:
  stage: deploy
  only:
    - tags
  except:
    - branches
  script:
    - make release
  artifacts:
    paths:
      - "*.pdf"
      - "*.png"
