language: minimal
sudo: required
dist: trusty
before_install:
- sudo apt-get -qq update && sudo apt-get install -y --no-install-recommends texlive-fonts-recommended texlive-latex-extra texlive-fonts-extra dvipng texlive-latex-recommended latex-beamer texlive-lang-german texlive-extra-utils cm-super
- wget http://tubslatex.ejoerns.de/1.1.0/texlive-tubs_1.1.0debian.deb
- sudo dpkg -i texlive-tubs_1.1.0debian.deb
script:
- make release
notifications:
  email:
    recipients:
      - tilman@tilman.ninja
