#!/usr/bin/env bash
echo "% WARNING! This file is autogenerated, do not change it by hand! Change $1 or scripts/dokuwiki_table_to_tex.sh instead!" > $2
echo '\begin{tabularx}{\textwidth}{|X|p{5cm}|p{3.6cm}|p{4cm}|}' >> $2
awk 'BEGIN { FS="[|^]"} {gsub(" ?\\(\\[\\[", "\\footnote{\\url{"); gsub("]]\\)", "}}"); print "\\hline" $2 "&" $3 "&" $4 "&" $5 "\\\\"}' $1 >> $2
echo '\hline' >> $2
echo '\end{tabularx}' >> $2