#!/usr/bin/env bash
echo "% WARNING! This file is autogenerated, do not change it by hand! Change $1 or scripts/dokuwiki_table_to_tex.sh instead!" > $2
echo '\begin{tabularx}{\textwidth}{@{}p{5cm}p{3cm}p{3.6cm}X@{}}' >> $2
awk 'BEGIN {FS="[|^]"; OFS="&"; ORS="\\\\ \n";} {gsub(" ?\\(\\[\\[", "\\footnote{\\url{"); gsub("]]\\)", "}}"); gsub(": ", ":~"); print (NR==1?"\\toprule":"\\midrule") $2,$3,$4,$5}' $1 >> $2
echo '\bottomrule' >> $2
echo '\end{tabularx}' >> $2